module.exports = {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      black: "#000000",
      white: "#ffffff",
      purple: "#3f3cbb",
      midnight: "#121063",
      metal: "#565584",
      tahiti: "#3ab7bf",
      silver: "#ecebff",
      "bubble-gum": "#ff77e9",
      bermuda: "#78dcca",
      borderBlue: "rgb(0, 22, 42)",
      darkBlue: "#001233",
      navblue: "#001845",
      bluenew: "#050f21",
      blue: "#001c55",
      lightBlue: "#0c2d8e",
      lightestBlue: "#1340c6 ",
      red: "#ef233c",
      grey: "#dedede",
    },
  },
  plugins: [],
};
